(executable
 (name correction_runner)
 (modules correction_runner sanitized trailing unreached)
 (libraries ppx_windtrap.runtime)
 (preprocess
  (pps ppx_windtrap)))

(rule
 (targets
  runner-log
  runner-exit
  sanitized.ml.corrected
  trailing.ml.corrected
  unreached.ml.corrected)
 (deps sanitized.ml trailing.ml unreached.ml)
 (action
  (run
   %{dep:../../cli/inline_runner/drive/drive.exe}
   --mask
   full-log
   --placeholder
   sanitized.ml
   --placeholder
   trailing.ml
   --placeholder
   unreached.ml
   --run
   runner
   %{dep:correction_runner.exe}
   inline-test-runner
   correction)))

(rule
 (alias runtest)
 (action
  (diff runner-exit.expected runner-exit)))

(rule
 (alias runtest)
 (action
  (diff runner-log.expected runner-log)))

(rule
 (alias runtest)
 (action
  (diff sanitized.ml.corrected.expected sanitized.ml.corrected)))

(rule
 (alias runtest)
 (action
  (diff trailing.ml.corrected.expected trailing.ml.corrected)))

(rule
 (alias runtest)
 (action
  (diff unreached.ml.corrected.expected unreached.ml.corrected)))
