(library
 (name windtrap_example_coverage)
 (modules calc half_a half_b stats)
 (instrumentation
  (backend ppx_windtrap.coverage)))

(test
 (name test_calc)
 (modules test_calc)
 (libraries windtrap windtrap_example_coverage))

(test
 (name test_a)
 (modules test_a)
 (libraries windtrap windtrap_example_coverage))

(test
 (name test_b)
 (modules test_b)
 (libraries windtrap windtrap_example_coverage))

(rule
 (alias cover)
 (deps
  (alias_rec runtest)
  (universe))
 (action
  (run %{bin:windtrap} coverage --min 80)))
