(*---------------------------------------------------------------------------
   Copyright (c) 2026 Invariant Systems. All rights reserved.
   SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(** The default ambient [Expect_test_config].

    Code generated by [ppx_windtrap] for [let%expect_test] references the
    {e unqualified} module name [Expect_test_config] — this module, once the
    build exposes it as a top-level module (matching ppx_expect's compatibility
    contract). A user module of the same name in scope shadows it:

    {[
      module Expect_test_config = struct
        include Expect_test_config

        let sanitize = Scrub.paths
      end

      let%expect_test "logs" = …
    ]}

    The generated code wraps every expect-test body in [Expect_test_config.run]
    at type [(unit -> unit) -> unit] and reads captured output through
    [Expect_test_config.sanitize]. Expect-test bodies are therefore synchronous:
    a monadic (Async-style) config's [run] does not fit that type and fails to
    {e compile} at the reference — never a silent behavioral change. *)

val run : (unit -> unit) -> unit
(** [run f] is [f ()]: runs an expect-test body. Override to wrap every
    expect-test body of a file (setup, error translation); the override must
    call [f] exactly once. *)

val sanitize : string -> string
(** [sanitize s] is [s]. Override to rewrite captured output before every
    comparison and correction — timestamps, temp paths, and other
    nondeterminism. *)
