(*---------------------------------------------------------------------------
   Copyright (c) 2026 Invariant Systems. All rights reserved.
   SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(** The default ambient [Expect_test_config].

    Code generated by [ppx_windtrap] for [let%expect_test] references the
    {e unqualified} module name [Expect_test_config] — this module, once the
    build exposes it as a top-level module (RFC compat mechanism (b), matching
    ppx_expect). A user module of the same name in scope shadows it:

    {[
      module Expect_test_config = struct
        include Expect_test_config

        let sanitize = Scrub.paths
      end

      let%expect_test "logs" = …
    ]}

    The generated code passes [Expect_test_config.run] at type
    [(unit -> unit) -> unit] and [Expect_test_config.sanitize] at type
    [string -> string] to {!Ppx_runtime.add_expect_test}. Expect-test bodies are
    therefore restricted to [IO.t = unit]: a monadic (Async-style) config's
    [run] does not fit that type and fails to {e compile} at the reference —
    never a silent behavioral change.

    [IO], [return], and [upon_unreleasable_issue] exist so that ppx_expect-era
    configs built by [include]-and-override keep compiling; windtrap itself
    consumes only [run] and [sanitize]. *)

(** The identity IO monad: expect-test bodies are synchronous. *)
module IO : sig
  type 'a t = 'a

  val return : 'a -> 'a t
  (** [return x] is [x]. *)
end

val run : (unit -> unit) -> unit
(** [run f] is [f ()]: runs an expect-test body. Override to wrap every
    expect-test body of a file (setup, error translation); the override must
    call [f] exactly once. *)

val sanitize : string -> string
(** [sanitize s] is [s]. Override to rewrite captured output before every
    comparison and correction — timestamps, temp paths, and other
    nondeterminism. *)

val upon_unreleasable_issue : [ `CR | `Warning_for_collector_testing ]
(** [upon_unreleasable_issue] is [`CR]. Vestigial, for ppx_expect config
    compatibility; windtrap ignores it. *)
