(*---------------------------------------------------------------------------
   Copyright (c) 2026 Invariant Systems. All rights reserved.
   SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(** The module path [ppx_windtrap]-generated code addresses the runtime by.

    [Ppx_windtrap_runtime.Ppx_runtime] is windtrap's [Ppx_runtime] — see
    [lib/ppx_runtime.mli] for the contract. Code generated by the rewriter and
    the [inline_tests] backend's runner reference the runtime only through this
    alias, so the spelling of windtrap's internal module layout stays out of
    generated code. Not for direct use. *)

module Ppx_runtime = Windtrap__Ppx_runtime
