(test
 (name test_mytool)
 (modules test_mytool mytool)
 (libraries windtrap)
 (deps help.expected)
 (action
  (progn
   (run %{test} --corrected)
   (diff? test_mytool.ml test_mytool.ml.corrected)
   (diff? help.expected help.expected.corrected))))

(library
 (name tokenizer)
 (modules tokens timing)
 (inline_tests)
 (preprocess
  (pps ppx_windtrap)))
