(*--------------------------------------------------------------------------
  Copyright (c) 2026 Thibaut Mattio. All rights reserved.
  SPDX-License-Identifier: ISC
  --------------------------------------------------------------------------*)

(* Stream and bounded-draw literals were independently computed for
   windtrap-next with arbitrary-precision arithmetic in Python and Ruby and
   are reused unchanged: [Seed.make]/[Seed.bits64] implement the same frozen
   SplitMix64 stream. Derivation, split, and mix-gamma literals were
   independently computed with an arbitrary-precision Python reference of the
   documented definitions. The seed-1234567 vector is the published SplitMix64
   reference vector (Vigna's splitmix64.c, as pinned by rand_xoshiro's test
   suite). None was generated by [Seed]. *)

open Windtrap
module Seed = Windtrap.Private.Seed

let hex_of_int64 value = Printf.sprintf "%016Lx" value

(* Compares with Int64 equality (via the canonical hex image) and renders
   in hex, which is how the frozen literals are written. *)
let hex64 = contramap hex_of_int64 string

let checkf condition format =
  Printf.ksprintf (fun message -> if not condition then fail message) format

let expect_hex ~label expected actual =
  equal ~msg:label string expected (hex_of_int64 actual)

let expect_seed ~label result =
  require_ok ~msg:label ~pp_error:Format.pp_print_string result

let expect_seed_error ~label = function
  | Error _ -> ()
  | Ok seed -> failf "%s: unexpectedly accepted %s" label (hex_of_int64 seed)

(* Token codec *)

let canonical_token_literals () =
  let vectors =
    [
      (0x0000000000000000L, "s1:0000000000000000");
      (0x0000000000000001L, "s1:0000000000000001");
      (0x0123456789abcdefL, "s1:0123456789abcdef");
      (0x7fffffffffffffffL, "s1:7fffffffffffffff");
      (0x8000000000000000L, "s1:8000000000000000");
      (0xffffffffffffffffL, "s1:ffffffffffffffff");
    ]
  in
  List.iter
    (fun (bits, text) ->
      equal ~msg:(text ^ " encode") string text (Seed.to_string bits);
      let decoded =
        expect_seed ~label:(text ^ " decode") (Seed.of_string text)
      in
      equal ~msg:(text ^ " bits") hex64 bits decoded)
    vectors

let all_token_patterns_round_trip () =
  (* A 64-bit LCG walk gives 1,024 well-spread bit patterns. *)
  let rec loop remaining bits =
    if remaining = 0 then ()
    else begin
      let text = Seed.to_string bits in
      let decoded =
        expect_seed ~label:("round trip " ^ text) (Seed.of_string text)
      in
      equal ~msg:("round trip " ^ text) hex64 bits decoded;
      let bits =
        Int64.add (Int64.mul bits 0x5851f42d4c957f2dL) 0x14057b7ef767814fL
      in
      loop (remaining - 1) bits
    end
  in
  loop 1_024 0x6a09e667f3bcc909L

let token_parser_rejects_malformed_text () =
  let rejected =
    [
      "";
      "s1:";
      "s1:000000000000000";
      "s1:00000000000000000";
      "s1:000000000000000A";
      "s1:000000000000000g";
      "s1:0000000000000000\x00";
      "s1:0000000000000000 ";
      " s1:0000000000000000";
      "S1:0000000000000000";
      "s01:0000000000000000";
      "s2:0000000000000000";
      "0000000000000000";
      "0x0000000000000000";
      "42";
      "+1";
      "-1";
    ]
  in
  List.iter
    (fun text ->
      expect_seed_error ~label:(String.escaped text) (Seed.of_string text))
    rejected

(* Stream *)

let stream_vectors =
  [
    ( 0x0000000000000000L,
      "zero",
      [
        "e220a8397b1dcdaf";
        "6e789e6aa1b965f4";
        "06c45d188009454f";
        "f88bb8a8724c81ec";
        "1b39896a51a8749b";
        "53cb9f0c747ea2ea";
      ] );
    ( 0x0000000000000001L,
      "one",
      [
        "910a2dec89025cc1";
        "beeb8da1658eec67";
        "f893a2eefb32555e";
        "71c18690ee42c90b";
        "71bb54d8d101b5b9";
        "c34d0bff90150280";
      ] );
    ( 0xffffffffffffffffL,
      "all bits",
      [
        "e4d971771b652c20";
        "e99ff867dbf682c9";
        "382ff84cb27281e9";
        "6d1db36ccba982d2";
        "b4a0472e578069ae";
        "d31dadbda438bb33";
      ] );
    ( 0x8000000000000000L,
      "high bit",
      [
        "481ec0a212a9f3db";
        "c46fa638a6309012";
        "61a685ffc80a8140";
        "592e268383e356f9";
        "0c8881ee746884d3";
        "4d7e6a268a67c5ff";
      ] );
  ]

let stream_matches_frozen_literals () =
  List.iter
    (fun (seed, label, outputs) ->
      let rec check_outputs index state = function
        | [] -> ()
        | expected :: remaining ->
            let word, state = Seed.bits64 state in
            expect_hex
              ~label:(Printf.sprintf "%s output %d" label index)
              expected word;
            check_outputs (index + 1) state remaining
      in
      check_outputs 1 (Seed.make seed) outputs)
    stream_vectors

let stream_matches_published_splitmix64_vector () =
  let state = Seed.make 1234567L in
  let first, state = Seed.bits64 state in
  let second, state = Seed.bits64 state in
  let third, _ = Seed.bits64 state in
  equal ~msg:"published output 1" hex64 6457827717110365317L first;
  equal ~msg:"published output 2" hex64 3203168211198807973L second;
  (* 9817491932198370423 mod 2^64, as a signed int64 *)
  equal ~msg:"published output 3" hex64 (-8629252141511181193L) third

let states_are_immutable_and_deterministic () =
  let initial = Seed.make 0L in
  let first, successor = Seed.bits64 initial in
  let repeated, repeated_successor = Seed.bits64 initial in
  equal ~msg:"reused initial output" hex64 first repeated;
  let second, _ = Seed.bits64 successor in
  let repeated_second, _ = Seed.bits64 repeated_successor in
  equal ~msg:"reused successor output" hex64 second repeated_second;
  expect_hex ~label:"first word" "e220a8397b1dcdaf" first;
  expect_hex ~label:"second word" "6e789e6aa1b965f4" second

let full_width_output_preserves_the_sign_bit () =
  let state = Seed.make 0L in
  let first, state = Seed.bits64 state in
  let _, state = Seed.bits64 state in
  let third, _ = Seed.bits64 state in
  is_true ~msg:"high-bit output is preserved as a full int64 pattern"
    (Int64.compare first 0L < 0);
  is_true ~msg:"low-half output keeps its sign bit clear"
    (Int64.compare third 0L >= 0)

(* Bounded draws *)

let bounded_edge_vectors () =
  let vectors =
    [
      (0x0000000000000001L, "0000000000000000");
      (0x0000000000000002L, "0000000000000001");
      (0x0000000000000003L, "0000000000000001");
      (0x000000000000000aL, "0000000000000005");
      (0x0000000000000100L, "00000000000000af");
      (0x7fffffffffffffffL, "6220a8397b1dcdb0");
      (0x4000000000000001L, "2220a8397b1dcdac");
    ]
  in
  List.iter
    (fun (bound, expected) ->
      let value, successor = Seed.below ~bound (Seed.make 0L) in
      expect_hex ~label:("bounded " ^ hex_of_int64 bound) expected value;
      checkf
        (Int64.compare value 0L >= 0 && Int64.compare value bound < 0)
        "bounded result %s is outside [0,%s)" (hex_of_int64 value)
        (hex_of_int64 bound);
      let next, _ = Seed.bits64 successor in
      expect_hex ~label:"one-word successor" "6e789e6aa1b965f4" next)
    vectors

let bounded_single_rejection_consumes_both_words () =
  let bound = 0x4000000000000001L in
  let value, successor = Seed.below ~bound (Seed.make 0x0123456789abcdefL) in
  expect_hex ~label:"one-rejection result" "1573529b34a1d090" value;
  let next, _ = Seed.bits64 successor in
  expect_hex ~label:"one-rejection successor" "2f90b72e996dccbe" next

let bounded_multiple_rejection_consumes_every_word () =
  let bound = 0x4000000000000001L in
  let value, successor = Seed.below ~bound (Seed.make 0x14L) in
  expect_hex ~label:"two-rejection result" "0079d22ed225a1f6" value;
  let next, _ = Seed.bits64 successor in
  expect_hex ~label:"two-rejection successor" "5c83eea29361787c" next

let bounded_rejects_invalid_bounds_before_sampling () =
  let state = Seed.make 0L in
  let expect_invalid ~label bound =
    raises_match ~msg:label
      (Exn.invalid_arg ~exact:"Seed.below: non-positive bound") (fun () ->
        Seed.below ~bound state)
  in
  expect_invalid ~label:"zero bound" 0L;
  expect_invalid ~label:"negative bound" (-1L);
  expect_invalid ~label:"min-int bound" Int64.min_int;
  let first, _ = Seed.bits64 state in
  expect_hex ~label:"invalid bounds leave the input state reusable"
    "e220a8397b1dcdaf" first

(* This oracle computes [2^64 mod bound] and an unsigned word remainder one
   bit at a time. For these small bounds every intermediate is a small signed
   value; it deliberately shares neither [unsigned_rem] nor negation with the
   production sampler. *)
let power_of_two_64_mod bound =
  let rec loop bits remainder =
    if bits = 64 then remainder
    else loop (bits + 1) (Int64.rem (Int64.mul remainder 2L) bound)
  in
  loop 0 1L

let unsigned_word_mod word bound =
  let rec loop bit remainder =
    if bit < 0 then remainder
    else
      let next_bit = Int64.logand (Int64.shift_right_logical word bit) 1L in
      let remainder =
        Int64.rem (Int64.add (Int64.mul remainder 2L) next_bit) bound
      in
      loop (bit - 1) remainder
  in
  loop 63 0L

let rec reference_below_small ~bound ~threshold state =
  let word, state = Seed.bits64 state in
  if Int64.compare word 0L >= 0 && Int64.compare word threshold < 0 then
    reference_below_small ~bound ~threshold state
  else (unsigned_word_mod word bound, state)

let bounded_sampling_agrees_with_independent_small_oracle () =
  let bounds = [ 1L; 2L; 3L; 5L; 10L; 17L; 257L; 65_537L ] in
  let seeds = [ 0L; 1L; 20L; 0x0123456789abcdefL; 0x8000000000000000L; -1L ] in
  List.iter
    (fun bound ->
      let threshold = power_of_two_64_mod bound in
      List.iter
        (fun seed ->
          let initial = Seed.make seed in
          let expected, expected_state =
            reference_below_small ~bound ~threshold initial
          in
          let actual, actual_state = Seed.below ~bound initial in
          let label =
            Printf.sprintf "bound %Ld seed %s" bound (hex_of_int64 seed)
          in
          equal ~msg:label hex64 expected actual;
          let expected_next, _ = Seed.bits64 expected_state in
          let actual_next, _ = Seed.bits64 actual_state in
          equal ~msg:(label ^ " consumption") hex64 expected_next actual_next)
        seeds)
    bounds

let bounded_draws_are_roughly_uniform () =
  let bound = 10L in
  let draws = 10_000 in
  let buckets = Array.make 10 0 in
  let state = ref (Seed.make 42L) in
  for _ = 1 to draws do
    let value, next = Seed.below ~bound !state in
    state := next;
    let index = Int64.to_int value in
    buckets.(index) <- buckets.(index) + 1
  done;
  Array.iteri
    (fun index count ->
      (* Expected 1,000 per bucket, standard deviation ~30; a 200 margin is
         over six sigma, catching gross bias without flakiness. *)
      checkf
        (count > 800 && count < 1200)
        "bucket %d holds %d of %d draws" index count draws)
    buckets

(* Derivation *)

let derivation_matches_frozen_literals () =
  (* Frozen at v3.0; independently computed from the documented definition. *)
  let vectors =
    [
      ("zero root, empty path", 0x0000000000000000L, "", 0, "8932c885a3fe960e");
      ( "zero root",
        0x0000000000000000L,
        "parser/round trip",
        0,
        "538edc95fb385999" );
      ( "index one",
        0x0000000000000000L,
        "parser/round trip",
        1,
        "f8e85f6cf19007ec" );
      ( "index 41",
        0x0000000000000000L,
        "parser/round trip",
        41,
        "78ab4d30d5215124" );
      ( "documented root",
        0x7be1d2c904aa31f5L,
        "parser/round trip",
        0,
        "d58e166440b6c9a8" );
      ( "one-byte path change",
        0x7be1d2c904aa31f5L,
        "parser/round trips",
        0,
        "ec0ade52565505bc" );
      ( "all-bits root",
        0xffffffffffffffffL,
        "suite/group/leaf name",
        99,
        "58c1fd40393ccc12" );
      ("high-bit root", 0x8000000000000000L, "a", 7, "61aea7fc71d6f792");
    ]
  in
  List.iter
    (fun (label, root, path, index, expected) ->
      expect_hex ~label expected (Seed.derive ~root ~path ~index))
    vectors

let derivation_hashes_raw_path_bytes () =
  (* Paths are hashed as raw bytes: NUL, non-ASCII UTF-8, and non-UTF-8 bytes
     all participate. Frozen at v3.0; independently computed in Python. *)
  let vectors =
    [
      ("lone NUL path", 0x0000000000000000L, "\x00", 0, "82b038124ef3e1a9");
      ("embedded NUL path", 0x0000000000000000L, "a\x00b", 0, "ffc9f641efb3864a");
      ( "UTF-8 path",
        0x7be1d2c904aa31f5L,
        "caf\xc3\xa9/na\xc3\xafve \xe2\x9c\x93",
        2,
        "dfaae0f8797a54f4" );
      ( "non-UTF-8 bytes path",
        0x7be1d2c904aa31f5L,
        "\xff\xfe raw \x80 bytes",
        5,
        "04b13d61346b793b" );
    ]
  in
  List.iter
    (fun (label, root, path, index, expected) ->
      expect_hex ~label expected (Seed.derive ~root ~path ~index))
    vectors;
  (* FNV-1a multiplies after every byte, so a trailing NUL still re-keys. *)
  not_equal ~msg:"a trailing NUL byte re-keys the stream" hex64
    (Seed.derive ~root:0L ~path:"a" ~index:0)
    (Seed.derive ~root:0L ~path:"a\x00" ~index:0)

let derivation_is_repeatable_and_sensitive () =
  let base = Seed.derive ~root:0L ~path:"parser/fields" ~index:0 in
  let again = Seed.derive ~root:0L ~path:"parser/fields" ~index:0 in
  equal ~msg:"repeatable derivation" hex64 base again;
  not_equal ~msg:"changing the root changes the case seed" hex64 base
    (Seed.derive ~root:1L ~path:"parser/fields" ~index:0);
  not_equal ~msg:"changing the path changes the case seed" hex64 base
    (Seed.derive ~root:0L ~path:"parser/other" ~index:0);
  not_equal ~msg:"changing the index changes the case seed" hex64 base
    (Seed.derive ~root:0L ~path:"parser/fields" ~index:1)

let derivation_is_distinct_across_paths_and_indices () =
  let module Int64_set = Set.Make (Int64) in
  let paths =
    [
      "a";
      "b";
      "a/b";
      "a/b/c";
      "parser/round trip";
      "parser/round trips";
      "suite/group/leaf name";
      "";
    ]
  in
  let seen = ref Int64_set.empty in
  let count = ref 0 in
  List.iter
    (fun path ->
      for index = 0 to 99 do
        let derived = Seed.derive ~root:0x7be1d2c904aa31f5L ~path ~index in
        checkf
          (not (Int64_set.mem derived !seen))
          "derived seed %s for %S/%d collides" (hex_of_int64 derived) path index;
        seen := Int64_set.add derived !seen;
        incr count
      done)
    paths;
  equal ~msg:"distinctness sweep coverage" int 800 !count

(* Split *)

let split_matches_frozen_literals () =
  let expect_outputs ~label state expected =
    let first, state = Seed.bits64 state in
    let second, _ = Seed.bits64 state in
    expect_hex ~label:(label ^ " word 1") (List.nth expected 0) first;
    expect_hex ~label:(label ^ " word 2") (List.nth expected 1) second
  in
  let fresh, continued = Seed.split (Seed.make 0L) in
  expect_outputs ~label:"fresh of zero" fresh
    [ "184c6c53fb60892d"; "d08944b9dffc3e93" ];
  expect_outputs ~label:"continued of zero" continued
    [ "06c45d188009454f"; "f88bb8a8724c81ec" ];
  let fresh, continued = Seed.split (Seed.make 0x0123456789abcdefL) in
  expect_outputs ~label:"fresh of nontrivial" fresh
    [ "06b8ca9bda6b2d7c"; "428c1e7538260226" ];
  expect_outputs ~label:"continued of nontrivial" continued
    [ "2f90b72e996dccbe"; "a2d419334c4667ec" ]

let split_gamma_regularity_branch_is_frozen () =
  (* [make 0xc3910c8d016b07d6] positions the second internal draw at zero,
     whose derived increment has a regular bit pattern; the mix-gamma
     regularity branch must fire and XOR in 0xaaaaaaaaaaaaaaaa. *)
  let fresh, continued = Seed.split (Seed.make 0xc3910c8d016b07d6L) in
  let first, state = Seed.bits64 fresh in
  let second, _ = Seed.bits64 state in
  expect_hex ~label:"regular-gamma fresh word 1" "f9a602a17425332e" first;
  expect_hex ~label:"regular-gamma fresh word 2" "237d30830cf39d4b" second;
  let first, state = Seed.bits64 continued in
  let second, _ = Seed.bits64 state in
  expect_hex ~label:"regular-gamma continued word 1" "e220a8397b1dcdaf" first;
  expect_hex ~label:"regular-gamma continued word 2" "6e789e6aa1b965f4" second

let split_is_deterministic_and_independent () =
  let state = Seed.make 0xdeadbeefcafebabeL in
  let fresh_a, continued_a = Seed.split state in
  let fresh_b, continued_b = Seed.split state in
  let take n state =
    let rec loop n state values =
      if n = 0 then List.rev values
      else
        let word, state = Seed.bits64 state in
        loop (n - 1) state (word :: values)
    in
    loop n state []
  in
  let words = list hex64 in
  equal ~msg:"splitting the same state twice gives the same fresh stream" words
    (take 4 fresh_a) (take 4 fresh_b);
  equal ~msg:"splitting the same state twice gives the same continued stream"
    words (take 4 continued_a) (take 4 continued_b);
  not_equal ~msg:"fresh and continued streams are distinct" words
    (take 4 fresh_a) (take 4 continued_a);
  not_equal ~msg:"fresh stream is distinct from the parent stream" words
    (take 4 fresh_a) (take 4 state)

let split_fresh_streams_are_distinct_across_seeds () =
  let module Int64_set = Set.Make (Int64) in
  let seen = ref Int64_set.empty in
  for seed = 0 to 99 do
    let fresh, _ = Seed.split (Seed.make (Int64.of_int seed)) in
    let word, _ = Seed.bits64 fresh in
    checkf
      (not (Int64_set.mem word !seen))
      "fresh stream for seed %d collides on its first word" seed;
    seen := Int64_set.add word !seen
  done

(* Entropy *)

let random_produces_distinct_seeds () =
  let rec distinct attempts =
    if attempts = 0 then false
    else if not (Int64.equal (Seed.random ()) (Seed.random ())) then true
    else distinct (attempts - 1)
  in
  is_true ~msg:"six entropy draws produced a single value" (distinct 3)

let tests =
  [
    test "canonical token literals" canonical_token_literals;
    test "all token patterns round trip" all_token_patterns_round_trip;
    test "token parser rejection matrix" token_parser_rejects_malformed_text;
    test "stream frozen literals" stream_matches_frozen_literals;
    test "stream published SplitMix64 vector"
      stream_matches_published_splitmix64_vector;
    test "states are immutable and deterministic"
      states_are_immutable_and_deterministic;
    test "full-width output sign bit" full_width_output_preserves_the_sign_bit;
    test "bounded edge vectors" bounded_edge_vectors;
    test "bounded single rejection" bounded_single_rejection_consumes_both_words;
    test "bounded multiple rejection"
      bounded_multiple_rejection_consumes_every_word;
    test "bounded invalid bounds" bounded_rejects_invalid_bounds_before_sampling;
    test "bounded independent oracle"
      bounded_sampling_agrees_with_independent_small_oracle;
    test "bounded rough uniformity" bounded_draws_are_roughly_uniform;
    test "derivation frozen literals" derivation_matches_frozen_literals;
    test "derivation hashes raw path bytes" derivation_hashes_raw_path_bytes;
    test "derivation repeatable and sensitive"
      derivation_is_repeatable_and_sensitive;
    test "derivation distinct across paths and indices"
      derivation_is_distinct_across_paths_and_indices;
    test "split frozen literals" split_matches_frozen_literals;
    test "split gamma regularity branch" split_gamma_regularity_branch_is_frozen;
    test "split deterministic and independent"
      split_is_deterministic_and_independent;
    test "split fresh streams distinct across seeds"
      split_fresh_streams_are_distinct_across_seeds;
    test "random produces distinct seeds" random_produces_distinct_seeds;
  ]
